const C=window.SELEKTA_CONFIG,S=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),$=id=>document.getElementById(id),safe=n=>n.toLowerCase().replace(/[^a-z0-9._-]/g,'-');
let editingMixId=null,editingEventId=null;
async function start(){let u=(await S.auth.getUser()).data.user;if(!u){$('login').hidden=false;return}let a=await S.from('admin_users').select('user_id').eq('user_id',u.id).maybeSingle();if(!a.data){await S.auth.signOut();$('loginMsg').textContent='Not authorized.';return}$('login').hidden=true;$('dash').hidden=false;refresh()}
$('loginForm').onsubmit=async e=>{e.preventDefault();let r=await S.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error)$('loginMsg').textContent=r.error.message;else start()};$('logout').onclick=async()=>{await S.auth.signOut();location.reload()};
async function upload(bucket,file,user,id){let path=`${user.id}/${id}-${safe(file.name)}`,r=await S.storage.from(bucket).upload(path,file,{upsert:false});if(r.error)throw r.error;return path}

function resetMixForm(){editingMixId=null;$('mixForm').reset();$('mf').setAttribute('required','');$('mixForm').querySelector('button').textContent='Publish Mix';$('mixCancel')?.remove()}
function resetEventForm(){editingEventId=null;$('eventForm').reset();$('ef').setAttribute('required','');$('eventForm').querySelector('button').textContent='Publish Event';$('eventCancel')?.remove()}

window.editMix=async id=>{let x=(await S.from('mixes').select('*').eq('id',id).single()).data;if(!x)return;editingMixId=id;$('mt').value=x.title||'';$('md').value=x.description||'';$('mf').removeAttribute('required');let btn=$('mixForm').querySelector('button');btn.textContent='Update Mix';if(!$('mixCancel')){let c=document.createElement('button');c.type='button';c.id='mixCancel';c.className='btn ghost';c.textContent='Cancel edit';c.onclick=resetMixForm;btn.after(c)}$('mixForm').scrollIntoView({behavior:'smooth'})};

window.editEvent=async id=>{let x=(await S.from('events').select('*').eq('id',id).single()).data;if(!x)return;editingEventId=id;$('en').value=x.name||'';$('et').value=x.event_type||'';$('ed').value=x.event_date||'';$('ev').value=x.venue||'';$('ep').value=x.ticket_price??'';$('ex').value=x.description||'';$('ef').removeAttribute('required');let btn=$('eventForm').querySelector('button');btn.textContent='Update Event';if(!$('eventCancel')){let c=document.createElement('button');c.type='button';c.id='eventCancel';c.className='btn ghost';c.textContent='Cancel edit';c.onclick=resetEventForm;btn.after(c)}$('eventForm').scrollIntoView({behavior:'smooth'})};

$('mixForm').onsubmit=async e=>{e.preventDefault();$('mixMsg').textContent=editingMixId?'Updating…':'Uploading…';try{let u=(await S.auth.getUser()).data.user,id=editingMixId||crypto.randomUUID(),patch={title:$('mt').value,description:$('md').value};if($('mf').files[0])patch.audio_path=await upload('mixes',$('mf').files[0],u,id);if($('mc').files[0])patch.cover_path=await upload('covers',$('mc').files[0],u,id);let r=editingMixId?await S.from('mixes').update(patch).eq('id',id):await S.from('mixes').insert({...patch,cover_path:patch.cover_path||null});if(r.error)throw r.error;$('mixMsg').textContent=editingMixId?'Updated.':'Published.';resetMixForm();refresh()}catch(x){$('mixMsg').textContent=x.message}};

$('eventForm').onsubmit=async e=>{e.preventDefault();$('eventMsg').textContent=editingEventId?'Updating…':'Uploading…';try{let u=(await S.auth.getUser()).data.user,id=editingEventId||crypto.randomUUID(),patch={name:$('en').value,event_type:$('et').value,event_date:$('ed').value,venue:$('ev').value,ticket_price:Number($('ep').value),description:$('ex').value};if($('ef').files[0])patch.poster_path=await upload('event-posters',$('ef').files[0],u,id);let r=editingEventId?await S.from('events').update(patch).eq('id',id):await S.from('events').insert(patch);if(r.error)throw r.error;$('eventMsg').textContent=editingEventId?'Updated.':'Published.';resetEventForm();refresh()}catch(x){$('eventMsg').textContent=x.message}};

async function refresh(){let m=await S.from('mixes').select('id,title,created_at').order('created_at',{ascending:false}),e=await S.from('events').select('id,name,event_date,venue').order('event_date',{ascending:false});$('list').innerHTML='<h3>Mixes</h3>'+((m.data||[]).map(x=>`<p>${x.title} <button class="btn ghost" onclick="editMix('${x.id}')">Edit</button> <button class="danger" onclick="delMix('${x.id}')">Delete</button></p>`).join('')||'<p>None</p>')+'<h3>Events</h3>'+((e.data||[]).map(x=>`<p>${x.name} — ${x.venue} <button class="btn ghost" onclick="editEvent('${x.id}')">Edit</button> <button class="danger" onclick="delEvent('${x.id}')">Delete</button></p>`).join('')||'<p>None</p>')}
window.delMix=async id=>{if(!confirm('Delete mix?'))return;let x=(await S.from('mixes').select('audio_path,cover_path').eq('id',id).single()).data;if(x?.audio_path)await S.storage.from('mixes').remove([x.audio_path]);if(x?.cover_path)await S.storage.from('covers').remove([x.cover_path]);await S.from('mixes').delete().eq('id',id);refresh()};window.delEvent=async id=>{if(!confirm('Delete event?'))return;let x=(await S.from('events').select('poster_path').eq('id',id).single()).data;if(x?.poster_path)await S.storage.from('event-posters').remove([x.poster_path]);await S.from('events').delete().eq('id',id);refresh()};start();
