const C=window.SELEKTA_CONFIG,S=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY),$=id=>document.getElementById(id);let events=[],current=null,qty=1;
$('menu').onclick=()=>$('nav').classList.toggle('on');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>$('nav').classList.remove('on'));
const url=(bucket,path)=>S.storage.from(bucket).getPublicUrl(path).data.publicUrl,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){let m=await S.from('mixes').select('*').eq('published',true).order('created_at',{ascending:false});$('mixesGrid').innerHTML=m.error?'<p>Unable to load mixes.</p>':m.data?.length?m.data.map(x=>`<article class="mix"><img src="${x.cover_path?url('covers',x.cover_path):'assets/default-cover.svg'}"><div class="pad"><h3>${esc(x.title)}</h3><p>${esc(x.description||'Selekta Evanoh Mix')}</p><audio controls preload="none" src="${url('mixes',x.audio_path)}"></audio><a class="download" href="${url('mixes',x.audio_path)}" download>↓ Download mix</a></div></article>`).join(''):'<p>No mixes yet.</p>';
let e=await S.from('events').select('*').eq('published',true).order('event_date',{ascending:true});events=e.data||[];$('eventsGrid').innerHTML=e.error?'<p>Unable to load events.</p>':events.length?events.map((x,i)=>`<article class="event" data-i="${i}"><img src="${url('event-posters',x.poster_path)}"><div class="pad"><small>${date(x.event_date)}</small><h3>${esc(x.name)}</h3><p>${esc(x.venue)} • ${esc(x.event_type)}</p></div></article>`).join(''):'<p>No upcoming events yet.</p>';document.querySelectorAll('.event').forEach(x=>x.onclick=()=>openEvent(events[+x.dataset.i]));}
function date(x){return new Date(x+'T00:00:00').toLocaleDateString('en-KE',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase()}
function openEvent(e){current=e;qty=1;$('poster').src=url('event-posters',e.poster_path);$('edate').textContent=date(e.event_date);$('ename').textContent=e.name;$('edesc').textContent=e.description;$('evenue').textContent=e.venue;$('etype').textContent=e.event_type;$('eprice').textContent='KSh '+Number(e.ticket_price).toLocaleString();$('qty').textContent=qty;total();$('payStatus').textContent='';$('modal').classList.add('on');document.body.style.overflow='hidden'}function total(){$('total').textContent='KSh '+(Number(current.ticket_price)*qty).toLocaleString()}function close(){ $('modal').classList.remove('on');document.body.style.overflow=''}$('close').onclick=close;$('modal').onclick=e=>{if(e.target===$('modal'))close()};$('minus').onclick=()=>{qty=Math.max(1,qty-1);$('qty').textContent=qty;total()};$('plus').onclick=()=>{qty=Math.min(20,qty+1);$('qty').textContent=qty;total()};
$('bookingForm').onsubmit=async e=>{e.preventDefault();let q={name:$('#bn').value,contact:$('#bc').value,event_date:$('#bd').value,event_type:$('#bt').value,venue:$('#bv').value,details:$('#bdetails').value};let r=await S.from('booking_requests').insert(q);let f=await fetch(e.target.action,{method:'POST',body:new FormData(e.target),headers:{Accept:'application/json'}});$('bookStatus').textContent=f.ok?'Booking request received. Evanoh will reply within 48 hours.':r.error?'Could not send booking request. Please WhatsApp +254703187388.':'Booking saved, but email notification failed. Please WhatsApp +254703187388.';if(f.ok||!r.error)e.target.reset()};
$('pay').onclick=async()=>{let p=$('phone').value.trim();if(!/^((07|01)\d{8}|254[17]\d{8})$/.test(p)){$('payStatus').textContent='Enter a valid Safaricom number.';return}$('pay').disabled=true;$('payStatus').textContent='Sending M-Pesa prompt…';let r=await S.functions.invoke('mpesa-stk-push',{body:{event_id:current.id,quantity:qty,phone:p}});if(r.error||!r.data?.ok){$('payStatus').textContent=r.data?.message||'Payment could not be started.';$('pay').disabled=false;return}let id=r.data.payment_id;$('payStatus').textContent='Check your phone and enter your M-Pesa PIN.';for(let i=0;i<20;i++){await new Promise(x=>setTimeout(x,3000));let q=await S.functions.invoke('payment-status',{body:{payment_id:id}});if(q.data?.status==='paid'){$('payStatus').innerHTML='Payment confirmed. Ticket code: <b>'+esc(q.data.ticket_code)+'</b>';$('pay').disabled=false;return}if(['failed','cancelled'].includes(q.data?.status)){break}}$('payStatus').textContent='Payment is still processing. Keep your M-Pesa confirmation message.';$('pay').disabled=false};load();
